services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.Api/Dockerfile

  techecommerce:
    image: ${DOCKER_REGISTRY-}techecommerce
    build:
      context: .
      dockerfile: TechEcommerce/Dockerfile

  mongoserver:
   image: mongo:latest
   container_name: mongoserver
   restart: always
   ports:
    - "27017:27017"
   volumes: 
    - mongodb_data:/data/db/
   networks:
    - backend
   environment:
    MONGO_INITDB_DATABASE: catalog


  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Cart/Cart.Api/Dockerfile
   
  cartdb:
    image: redis:alpine

networks:    
  backend:
    name: backend

volumes:
  mongodb_data:

